deployment:
  tasks:
    - export DEPLOYPATH=/home/u3627877/repositories/testing-deployment
    - /bin/cp public/index.html $DEPLOYPATH
    - /bin/cp public/styles.css $DEPLOYPATH
    - /bin/cp public/script.js $DEPLOYPATH
    - /bin/cp -R public/our-partners $DEPLOYPATH
    - /bin/cp -R public/terms $DEPLOYPATH
    - /bin/cp -R public/fonts $DEPLOYPATH
    - /bin/cp -R public/images $DEPLOYPATH
    - /bin/cp -R public/uploads $DEPLOYPATH