---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u3627877/vera.partners 
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R uploads $DEPLOYPATH
