backend:
  name: git-gateway
  branch: main
media_folder: "src/uploads/partners"
public_folder: "/uploads/partners"
collections:
  - name: "partner"
    label: "Partner"
    folder: "src/data/partners"
    identifier_field: name
    create: true
    fields: 
      - { label: 'Название', name: 'name', widget: 'string' }
      - { label: 'Ссылка', name: 'link', widget: 'string' }
      - { label: 'Описание', name: 'description', widget: 'markdown' }
      - { label: 'Изображение', name: 'image', widget: 'image' }