name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build static files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js
      uses: actions/setup-node@main
      with:
        node-version: 16.x

    - name: Install deps and build
      run: |
        npm install
        npm run build

    - name: Update deploy branch
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: deploy
        FOLDER: public
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
