name: Publish Website to CPanel
on:
  push:
    branches:
      - main
jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get Latest Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Use Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Build Project
      run: |
        npm install
        npm run build
    
    - name: Deploy 
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
